in:
  type: file
  path_prefix: bench/dummy
  parser:
    type: csv
    columns:
      - {name: timestamp, type: string}
filters:
  - type: timestamp_format
    columns:
      - {name: timestamp, from_format: ["yyyy-MM-dd hh:mm:ss.nnnnnnnnn"], to_format: "%Y-%m-%d"}
out:
  type: "null"
