in:
  type: file
  path_prefix: bench/dummy
  parser:
    type: csv
    columns:
      - {name: timestamp, type: string}
filters:
  - type: timestamp_format
    stop_on_invalid_record: true
    columns:
      - {name: timestamp, from_format: ["yyyy-MM-dd HH:mm:ss.SSSSSSSSS"], to_format: "%Y-%m-%d"}
out:
  type: "null"
