in:
  type: file
  path_prefix: bench/dummy
  parser:
    type: csv
    columns:
      - {name: timestamp, type: string}
filters:
  - type: timestamp_format
    stop_on_invalid_record: true
    columns:
      - {name: timestamp, from_format: ["%Y-%m-%d %H:%M:%S.%N"], to_format: "yyyy-MM-dd"}
out:
  type: "null"
